pom.xml
src/main/java/com/vaadin/flow/component/dialog/Dialog.java
src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java

Used `<flow-component-renderer>` to be able to add and remove components in a dialog. Removed most of the boring old demos and added a demo about a confirmation-dialog.
Also, now dialog adds itself to the `<body>` when opened, if it's not yet attached. So users can just call dialog.open() without adding the component anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/19)

Implement adding/removing components

---

src/main/java/com/vaadin/flow/component/dialog/Dialog.java

The component didn't work on IE11 because the <template> was set as innerHTML, and the <template>-polyfill couldn't handle that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/29)

Properly construct the template-element instead of setting as innerHTML

---

src/main/java/com/vaadin/flow/component/dialog/Dialog.java
src/test/java/com/vaadin/flow/component/dialog/DialogTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/43)

getChildren now returns what the internal container has

---

src/main/java/com/vaadin/flow/component/dialog/Dialog.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplateIT.java
src/test/java/com/vaadin/flow/component/dialog/tests/InitiallyOpenedDialogPageIT.java

The Dialog is removed when it is automatically added to the DOM during the `open()` call. If the user decides to add it to the DOM by himself, then the Dialog is not removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/44)

Dialog is now removed from the DOM when closed

---

src/main/java/com/vaadin/flow/component/dialog/Dialog.java

to emphasize that they don't necessarily listen to opening and closing the dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/45)

Improve javadocs of attach and detach listeners

---

pom.xml
src/main/java/com/vaadin/flow/component/dialog/Dialog.java
src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialogOverlay.java
src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java

The new generated component uses `PropertyChangeListener` for `OpenedChangeEvents`, which means that server-side property-changes fire events immediately instead of waiting for client-side dom-event.
For removing the component when closing I had to revert to using the dom-event, because the value-change doesn't work after the component is removed.
The API change was that there's now a parameter for the lambda in `beforeClientResponse`.
I also added tests to verify that `OpenedChangedEvents` work properly: no extra initial event fired (currently fixed with the workaround) and correct value for `isFromClient`
Also, updated webjar to `2.0.0-beta2`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Update generated component and fix API change

---

src/main/java/com/vaadin/flow/component/dialog/Dialog.java
src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java

Client-side can close the dialog synchronously when the user presses escape or
clicking outside. This makes server side unable to prevent closing if there
are unsave changes etc. With this change, server side can listen to an event
and decide whether to close the dialog.
Fixes #37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/52)

Inform server that user wants to close the dialog.

---

src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java

A demo for server-side validation was missing. Adding it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/56)

Adding demo for demoing how to handle server-side close validation

---

pom.xml
src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplateIT.java
src/test/java/com/vaadin/flow/component/dialog/tests/InitiallyOpenedDialogPageIT.java

Fix IT tests, as `flow-component-renderer` is not inside the `vaadin-overlay` shadowroot
anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/58)

 Update vaadin-dialog to 2.0.0-beta4

---

src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java

This is an issue fixed in lates vaadin-overlay release, thus
we do not have to fix anything, just test that it works.
Closes #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/59)

Adding a test for checking that we can focus internal elements.

---

pom.xml
src/main/java/com/vaadin/flow/component/dialog/Dialog.java
src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
src/test/java/com/vaadin/flow/component/dialog/tests/CloseListenerReopenDialogIT.java
src/test/java/com/vaadin/flow/component/dialog/tests/CloseListenerReopenDialogPage.java

Fixes #80 , #68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/91)

Correctly handle request to close from client-side

---

src/test/java/com/vaadin/flow/component/dialog/tests/CloseListenerReopenDialogIT.java

After close the dialog, the checking should not wait for the overlay to
present
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/93)

Correct the IT test

---

src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java

Adding a wait for the dialog overlay to disappear, to fix two unstable tests in DialogTestPageIT (openDialogAddComponentAtFirst, openDialogAddComponentAtIndex)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/106)

Fixing unstable tests in DialogTestPageIT

---

src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java

Cherry-picks:
- Adding a wait for the dialog overlay to disappear to fix two unstable tests(openDialogAddComponentAtFirst, openDialogAddComponentAtIndex) (#106)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/114)

1.2 cherry picks

---

vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

When a route leads to a component annotated with @PreserveOnRefresh, all direct UI children (such as dialogs and notifications) are transferred to the new UI (see https://github.com/vaadin/flow/issues/5608). This requires the dialog to update the renderer on attach.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/128)

Update renderer innerHTML on each attach to work properly with @PreserveOnRefresh

---

pom.xml
vaadin-dialog-flow-demo/pom.xml
vaadin-dialog-flow-integration-tests/pom-bower-mode.xml
vaadin-dialog-flow-integration-tests/pom.xml
vaadin-dialog-flow-testbench/pom.xml
vaadin-dialog-flow/pom.xml

Version was upgraded twice first from 1.4 to 2.0 and then 3.0
2.0 shold be the correct version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/129)

Downgrade major to 2.0 as the latest release was 1.3

---

vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

This prevents the following warning in projects using vaadin-dialog-flow
>[WARNING] Use the './' prefix for resources in JAR files: 'flow-component-renderer.js', please update your component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/133)

Use the './' prefix in @JsModule

---

vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java

- Add getters and setters for draggable, resizable and modal APIs
- Add javadoc describing the functionalities
- Add demo
- Add unit tests
Fix #150

Add Draggable, Resizable and Modal APIs

---

vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

- Add resize event and method to add listener
- Add default listener to sync client width and height values on every resize
- Add test for checking that dimension is preserved after closing and reopening the same dialog after resize
Closes #151

Add DialogResizeEvent and sync width/height

---

vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

- Make call to set overlay dimension on setWidth/setHeight
- Add tests to cover cases the bug was present
Fixes #156

Fix setting dimension for opened/attached dialog

---

vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
vaadin-dialog-flow-integration-tests/pom.xml
vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogView.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java

Labels should be used in combination with some component as a caption; thus, replacing incorrect usage of them. Instead, `Text` and `Span` are used
Porting https://github.com/vaadin/vaadin-dialog-flow/pull/160 to 2.1 branch for V14

Replace labels with Span's and Text's in demo view

---

vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/pom.xml
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java

Dialog Flow has a div container where all child element are appended to. That prevented the dialog from being dragged when it started from that container.
`vaadin-dialog@#2.3.0-alpha3` allows to set a class "`draggable`" to mark an element inside the dialog as a valid dragging target.
Fixes #165

Allow dragging dialog from div container

---

vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/pom.xml
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java

This PR contains the following changes made for Dialog Flow `2.1` (_eventually it can be updated to other changes made to `2.1`_):
- 9e6fba0 Fix setting dimension for opened/attached dialog (#157)
- 0dbe08e Add DialogResizeEvent and sync width/height (#155)
- 4a315cc Add Draggable, Resizable and Modal APIs (#153)
- e7b8782 Fix vaadin dialog full size (#147)
- 982bcf4 Allow dragging dialog from div container (#166)
- e2b11a9 fix: isDaggable -> isDraggable typo (#172)
**NOTE** Preferably it would be better to not **_squash_** but **_rebase merge_** to preserve history.

Cherry-pick new API from 2.1 version

---

vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

Fixes https://github.com/vaadin/vaadin-dialog-flow/issues/185
Currently, the content wrapper is a `block`-element. This PR makes it an `inline-block`-element so it wouldn't collapse margins https://www.sitepoint.com/collapsing-margins/

fix: prevent content margin collapse

---

vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java

Fix #168
Use the same approach as done in width/height setters.
Blocked by https://github.com/vaadin/vaadin-dialog/pull/192

fix: set values for min/max height/width correctly 

---

vaadin-dialog-flow-integration-tests/pom.xml
vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java

Previously, a fix was introduced to prevent vertical scrollbar from showing when content had margin due some margin collapse, so the fix was to force the container to be `inline-block`. This caused a regression for, eg. a VerticalLayout with no padding, which now makes visible scrollbar.
This change makes the internal container to be a flex box with column direction.
Fixes #225

fix: prevent showing scrollbar when content fits
