vaadin/vaadin-dialog-flow

- pom.xml
- src/test/java/com/vaadin/ui/dialog/DialogIT.java
add DialogIT test class;
overwrite flow-html-components version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/5)
> Add dialog component IT test

- .gitignore
- pom.xml
- src/test/java/com/vaadin/ui/dialog/DialogIT.java
- src/test/java/com/vaadin/ui/dialog/DialogView.java
+ This is done because otherwise the parent-pom, flow-component, can't
be resolved.
- Remove the main method from demo and IT class.
+ edit gitignore file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/6)
> Add Flow repositories to pom.xml

- README.md
- pom.xml
- src/test/java/com/vaadin/ui/dialog/DialogIT.java
- src/test/java/com/vaadin/ui/dialog/DialogView.java
this is related to ticket vaadin/flow#2795
+add Route title, as it can cause conflict to use default route;
+override getTestPath();
+Update parent and dependency version to SNAPSHOT;
+Update README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/10)
> Prepare to build Demo jar of the component

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/11)
> add button and ordered-layout dependencies for test

- src/test/java/com/vaadin/ui/dialog/demo/DialogView.java
- src/test/java/com/vaadin/ui/dialog/tests/DialogIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/15)
> Refactor the repo structure

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialogOverlay.java
- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
Part of the package rename #3032
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/16)
> Rename package com.vaadin.ui to com.vaadin.flow.component

- pom.xml
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialogOverlay.java
- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
The part of the package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/17)
> Update imports due package rename in server module

- src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/21)
> Correct import in IT tests

- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/22)
> Update generated files and add lumo style to demos

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/24)
> Dont fail when has a parent but not attached. Fixes #23

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialogOverlay.java
update the generated file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/25)
> Update Java API

- pom.xml
- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
renaming repository id;
add logging dependency;
remove HtmlImport in component demo file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/26)
> Using new webjars

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
Add IT test for the new api.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/31)
> Add OpenedChangeListener as public Java API

- pom.xml
- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplateIT.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplatePage.java
- src/test/java/com/vaadin/flow/component/dialog/tests/TestTemplate.java
- src/test/webapp/frontend/src/test-template.html
Related to https://github.com/vaadin/flow/issues/3513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/38)
> Fix for Dialogs with a PolymerTemplate inside. Added tests.

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- src/test/java/com/vaadin/flow/component/dialog/tests/InitiallyOpenedDialogPage.java
- src/test/java/com/vaadin/flow/component/dialog/tests/InitiallyOpenedDialogPageIT.java
Fixes #32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/41)
> Defer attaching dialog to the UI instance

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Fixes #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/51)
> Add check against null for UI instance

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
Fixes #35
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/57)
> Implement HasSize interface. Fixes #35

- src/test/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/62)
> Add a demo for styling the content of a dialog

- pom.xml
- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/65)
> Update webjars and generated code

- pom.xml
Part of #3630
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/66)
> Use provided scopes for Flow deps

- .gitignore
- pom.xml
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
Added test that empty dialog has size.
Fixes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71)
> Update dialog to 2.0.2

- pom.xml
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogSerializableTest.java
Related to vaadin/platform#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/72)
> Add serialization test

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/81)
> Fix flow dependency type

- pom.xml
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithComboBoxIT.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithComboBoxPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/77)
> Add a test case for #4268

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/83)
> Update Readme about the branch scheme

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/85)
> Update webjars with material theme

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
Add tests;
part of vaadin/flow#4437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/90)
> Correct the APIs for adding Component at index

- pom.xml
- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
- src/test/java/com/vaadin/flow/component/dialog/tests/CloseListenerReopenDialogIT.java
- src/test/java/com/vaadin/flow/component/dialog/tests/CloseListenerReopenDialogPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/92)
> Correctly handle request to close from client-side (#91)

- src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
Part of the fix for #4600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/96)
> Make addComponentAtIndex logic FW8 compatible

- src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/99)
> Update java wrapper to stable version

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/112)
> <flow.version>1.3-SNAPSHOT</flow.version>

- README.md
- vaadin-dialog-flow-demo/pom.xml
- vaadin-dialog-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/115)
> Update readme and add logger dependency

- pom.xml
- vaadin-dialog-flow-demo/pom.xml
- vaadin-dialog-flow-integration-tests/pom.xml
- vaadin-dialog-flow-testbench/pom.xml
- vaadin-dialog-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/119)
> Update to next minor

- vaadin-dialog-flow-integration-tests/pom.xml
- vaadin-dialog-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/125)
> Make TB artifactId consistent with other components

- vaadin-dialog-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/132)
> Bump combo-box version to latest for ITs

- vaadin-dialog-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/131)
> Remove vaadin-components-testbench

- .gitignore
- vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
Fixes #135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/136)
> Check element has not parent right before auto adding it to the UI

- .gitignore
- vaadin-dialog-flow-integration-tests/pom-bower-mode.xml
- vaadin-dialog-flow-integration-tests/pom.xml
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplateIT.java
- vaadin-dialog-flow-testbench/src/main/java/com/vaadin/flow/component/dialog/testbench/DialogElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/134)
> Prevent cyclic object error firefox

- vaadin-dialog-flow-demo/pom.xml
- vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
Fix #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/145)
> fix the buttons in the confirmation dialog demo

- pom.xml
- vaadin-dialog-flow-demo/pom.xml
- vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- vaadin-dialog-flow-integration-tests/pom-bower-mode.xml
- vaadin-dialog-flow-integration-tests/pom.xml
- vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow-testbench/pom.xml
- vaadin-dialog-flow/pom.xml
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Fix https://github.com/vaadin/vaadin-dialog/issues/142
Fix #103
> Fix vaadin dialog full size

- vaadin-dialog-flow/pom.xml
> Downgrade overlay webjar to 3.3.0

- vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
- vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogView.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogIT.java
Replace Label component with Text. Suits better the purpose of the example
Fixes https://github.com/vaadin/90min-dx-tasks/issues/96
> Replace labels in Dialog

- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
> Fix isDaggable -> isDraggable typo

- pom.xml
- vaadin-dialog-flow-demo/pom.xml
- vaadin-dialog-flow-integration-tests/pom-bower-mode.xml
- vaadin-dialog-flow-integration-tests/pom.xml
- vaadin-dialog-flow-testbench/pom.xml
- vaadin-dialog-flow/pom.xml
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
> Bump versions for V14.3

- vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java
Fixes https://github.com/vaadin/vaadin-dialog-flow/issues/89
> Improve demo

- vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow/pom.xml
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
> Bump Web Component version to 2.4.5

- vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow/pom.xml
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
- vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
> Bump Web Component version to 2.5.2

- vaadin-dialog-flow-integration-tests/pom-bower-mode.xml
- vaadin-dialog-flow-integration-tests/pom.xml
- vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogTestPage.java
- vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java
- vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
> fix: prevent showing scrollbar when content fits (#232) 
